export enum ErrorCodes {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  ONLY_PENDING_TRANSACTIONS_CAN_BE_APPROVED = 'ONLY_PENDING_TRANSACTIONS_CAN_BE_APPROVED',
  ONLY_PENDING_TRANSACTIONS_CAN_BE_REJECTED = 'ONLY_PENDING_TRANSACTIONS_CAN_BE_REJECTED',
  ONLY_PENDING_TRANSACTIONS_CAN_BE_UPDATED = 'ONLY_PENDING_TRANSACTIONS_CAN_BE_UPDATED',
}